# Generated by Django 2.0.3 on 2020-09-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100)),
                ('d_small', models.FloatField()),
                ('d_large', models.FloatField()),
                ('d_image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('p_image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Regular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=100)),
                ('r_small', models.FloatField()),
                ('r_large', models.FloatField()),
                ('r_image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('salad_image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sicilian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_small', models.FloatField()),
                ('s_large', models.FloatField()),
                ('s_image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_small', models.FloatField()),
                ('sub_large', models.FloatField()),
                ('sub_image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
            ],
        ),
    ]
