# Generated by Django 2.0.3 on 2020-11-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_confirmedorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedorders',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='confirmedorders',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
