# Generated by Django 2.0.3 on 2020-11-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20201102_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedorders',
            name='item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='confirmedorders',
            name='item1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='confirmedorders',
            name='item2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='confirmedorders',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmedorders',
            name='quantity1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmedorders',
            name='quantity2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
