# Generated by Django 2.0.3 on 2020-11-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20201102_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedorders',
            name='orders',
        ),
    ]
