# Generated by Django 2.0.3 on 2020-11-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_confirmedorders_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedorders',
            name='status',
            field=models.CharField(choices=[('1', 'Your food is getting ready'), ('2', 'Out for Delivery'), ('3', 'Delivered')], default='1', max_length=100),
        ),
    ]
