# Generated by Django 2.0.3 on 2020-11-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20201103_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedorders',
            name='status',
            field=models.CharField(choices=[('Your food is getting ready', '1'), ('Out for Delivery', '2'), ('Delivered', '3')], default='Your food is getting ready', max_length=100),
        ),
    ]
